#!/bin/bash
# COLOR VALIDATION
clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
f="\033[1;97;41m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
#INTALLER-UDP
UDPX="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
ISP=$(cat /root/.info/.isp)
CITY=$(cat /root/.info/.city)
IPVPS=$(curl -s ipv4.icanhazip.com)
NS=$(cat /etc/xray/dns)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d-%m-%Y')
TIMEZONE=$(printf '%(%H-%M-%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(curl -sS ipv4.icanhazip.com)
echo ""
izinsc="https://raw.githubusercontent.com/Ilham24022001/ijin/refs/heads/main/ijin"
# USERNAME
rm -f /usr/bin/user
username=$(curl ${izinsc} | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
# validity
rm -f /usr/bin/e
valid=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
echo "$valid" >/usr/bin/e
# DETAIL ORDER
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
clear
# CERTIFICATE STATUS
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
# VPS Information
DATE=$(date +'%Y-%m-%d')
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
}
mai="datediff "$Exp" "$DATE""

# Status Expired Or Active
Info="(${green}Active${NC})"
Error="(${RED}Expired${NC})"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"

# Getting CPU Information
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"

WKT=$(curl -s ipinfo.io/timezone )
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(curl -s ipv4.icanhazip.com)
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status | Geo Project
clear

#####INFOAKUN
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2
###########
KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC"
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"
########
r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
#clear
clear

function Newbie_Banner() {
clear
BOX_WIDTH=47
TEXT="$(cat /etc/xray/username)"
TEXT_LENGTH=${#TEXT}
TEXT_COLOR="\033[97;1m\033[41m"
RESET_COLOR="\033[0m"
LEFT_PADDING=$(( (BOX_WIDTH - TEXT_LENGTH) / 2 ))
RIGHT_PADDING=$(( BOX_WIDTH - TEXT_LENGTH - LEFT_PADDING ))
LEFT_SPACE=$(printf '\033[41m%*s\033[0m' $LEFT_PADDING '')
RIGHT_SPACE=$(printf '\033[41m%*s\033[0m' $RIGHT_PADDING '')
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
echo -e "\033[97;1m  \033[0m${LEFT_SPACE}${TEXT_COLOR}${TEXT}${RESET_COLOR}${RIGHT_SPACE} \033[97;1m \033[0m"
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
}



function Service_System_Operating() {
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
echo -e "\033[96;1m \e[97m SYSTEM          : $(cat /etc/os-release | grep -w ID | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/ID//g')     \033[0m "
echo -e "\033[96;1m \e[97m RAM             : $(free -m | awk 'NR==2 {print $2}')    \033[0m "
echo -e "\033[96;1m \e[97m UPTIME          : $(uptime -p | cut -d " " -f 2-10)\033[0m "
echo -e "\033[96;1m \e[97m IP VPS          : $(curl -s ipv4.icanhazip.com)     \033[0m "
echo -e "\033[96;1m \e[97m CITY            : $(cat /etc/xray/city)    \033[0m "
echo -e "\033[96;1m \e[97m ISP             : $(cat /etc/xray/isp)    \033[0m "
echo -e "\033[96;1m \e[97m DOMAIN          : $(cat /etc/xray/domain)    \033[0m "
echo -e "\033[96;1m───────────────────────────────────────────────────\033[0m"
echo -e "\033[97;1m             \033[0m \033[93;1m\033[0m \033[92;1m[ SERVICE STATUS ]\033[0m \033[97;1m \033[0m " 
}



function Service_Status() {
echo -e "\033[96;1m───────────────────────────────────────────────────\033[0m "
echo -e "\033[96;1m \e[0m\e[33m PROXY :\e[0m $status_haproxy  \e[0m|\e[33m NGINX :\e[0m $status_nginx  \e[0m|\e[33m XRAY :\e[0m $status_xray \e[0m| $status_dropbear  \e[96;1m   \e[0m "
}



function Acces_Use_Command() {
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
echo -e "\033[96;1m  \e[34m1.)\e[93m \e[97m SSH/OPENVPN         \e[34m7.)\e[93m \e[97m BOT TELEGRAM   \e[96;1m\e[0m"   
echo -e "\033[96;1m  \e[34m2.)\e[93m \e[97m XRAY MANAGER        \e[34m8.)\e[93m \e[97m UPDATE SCRIPT  \e[96;1m\e[0m"
echo -e "\033[96;1m  \e[34m3.)\e[93m \e[97m XRAY TROJAN         \e[34m9.)\e[93m \e[97m BACKUP RESTOR  \e[96;1m\e[0m"
echo -e "\033[96;1m  \e[34m4.)\e[93m \e[97m SLOWDNS            \e[34m10.)\e[93m \e[97m FEATURES       \e[96;1m\e[0m"
echo -e "\033[96;1m  \e[34m5.)\e[93m \e[97m NOOBZVPNS          \e[34m11.)\e[93m \e[97m REBOOT         \e[96;1m\e[0m"
echo -e "\033[96;1m  \e[34m6.)\e[93m \e[97m RENAME SC          \e[34m12.)\e[93m \e[97m MENU        \e[96;1m\e[0m"
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
echo -e "\033[96;1m                \e[31m\e[93m  \e[91m   [ EXIT ]          \e[96;1m\e[0m"
echo -e "\033[96;1m═══════════════════════════════════════════════════\033[0m "
echo -e "\033[96;1m┌──────────────────────────────────────────────────┐\033[0m"
echo -e "\033[96;1m   \e[0m\e[33m      kesuksesan itu dari diri sendiri \033[0m"
echo -e "\033[96;1m└──────────────────────────────────────────────────┘\033[0m"
}



function Select_Display() {
echo
read -p "Select From option [1/11 or x] :  " hallo
case $hallo in
1) clear ; m-ssh ;; # menu ssh
2) clear ; m-xray ;; # menu vmess
3) clear ; m-tro ;; # menu vles
4) clear ; sd ;; # menu trojan
5) clear ; m-noobz ;; # menu sadowsocks
6) clear ; Rename ;; # menu noobzvps
7) clear ; m-bot ;; # menu bot telegram
8) clear ; wget -q https://raw.githubusercontent.com/Ilham24022001/Gantengzz/main/update.sh && bash update.sh ;; #Update script
9) clear ; m-bkp ;; # menu backup
10) clear ; m-ftr ;; # menu managers
11)clear ; reboot ;; # menu managers
*) welcome ;; # Back To Home Welcome
esac
}


Newbie_Banner
Service_System_Operating
Service_Status
Acces_Use_Command
Select_Display







